@extends('layouts.app')

@section('content')
@include('layouts.header')
@include('partials.slider')
@include('partials.banner')
@include('services.services_showcase')
@include('partials.stats')
@include('partials.about')
@include('partials.services')
@include('partials.portfolio', ['projects' => $projects])
@include('partials.blog')
@include('partials.testimonies')
@includeIf($clients->isNotEmpty(), 'partials.clients')
@stop
