language: php

php:
  - 7.2
  - 7.3

before_script:
  - cp .env.travis .env
  - composer self-update
  - touch ./database/database.sqlite
  - wget https://www.dropbox.com/s/66syw88qjxclgfc/nova.zip
  - unzip nova.zip
  - printf "\n" | pecl install imagick
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --verbose

after_success:
    - bash <(curl -s https://codecov.io/bash) -t e0c83fab-4fe6-471a-8e62-f7e263b91602
