language: php

php:
  - 7.2
  - 7.3

before_script:
  - rm .env.example
  - cp .env.travis .env
  - composer self-update
  - touch ./database/database.sqlite
  - wget http://167.99.197.130/nova.zip
  - unzip nova.zip
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

script:
  - vendor/bin/phpunit
