language: php

php:
    - 7.1.3
    - 7.2.4
    - 7.2.8
    - 7.2.9

before_script:
    - rm .env.example
    - cp .env.travis .env
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-dist
    - php artisan key:generate

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -t b0d4fe37-3170-4170-a007-181ffee64e7d
